name: Ecommerce Web Automation

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

  workflow_dispatch:

  schedule:
    # Simulate monthly regression test execution
    - cron: '0 18 1 * *'

env:
  CI: true

permissions:
  contents: write

jobs:

  web-ui-test:

    runs-on: ubuntu-latest

    timeout-minutes: 20

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5

        with:
          python-version: "3.14"

      - name: Install Google Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Allure CLI
        run: |
            sudo apt update
            sudo apt install -y default-jre
            curl -o allure.tgz -OL https://github.com/allure-framework/allure2/releases/download/2.29.0/allure-2.29.0.tgz
            sudo tar -zxvf allure.tgz -C /opt/
            sudo ln -s /opt/allure-2.29.0/bin/allure /usr/bin/allure
            allure --version

      - name: Run Web UI Tests
        id: tests
        continue-on-error: true
        run: |
          echo "Triggered by: ${{ github.event_name }}"
          
          if [ "${{ github.event_name }}" = "schedule" ]; then
            echo "Running Regression Tests..."
            pytest -m "regression and not skip_ci" --junitxml=reports/junit.xml
          else
            echo "Running Smoke Tests..."
            pytest -m "smoke" --junitxml=reports/junit.xml
          fi

      - name: Generate Allure Report
        if: always()
        run: |
          allure generate \
          reports/allure-results \
          -o reports/allure-report \
          --clean

      - name: Deploy Allure Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: reports/allure-report

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: web-ui-allure-report
          path: reports/allure-report

      - name: Send Telegram Test Report
        if: always()
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_SERVER_URL: ${{ github.server_url }}
          GITHUB_RUN_ID: ${{ github.run_id }}

          ALLURE_REPORT_URL: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/

        run: |
          python utils/telegram_notifier.py

      - name: Return failure status for failed tests
        if: steps.tests.outcome == 'failure'
        run: exit 1